### ISSUE TITLE
开始就没看懂这个storybook的运行，所以提点问题

### ISSUE THREAD

**Issue by nightlye** [mindkitMap/outlineEditor#4]
首先应该是把outlineEditor克隆到本地，然后在终端安装并运行storybook吧？
原谅我是个新手，不是很清楚操作。
我克隆到本地，并且使用了如下代码：
`npx sb init`
'npm run storybook'
但是并没有打开什么窗口之类的。
![image](https://user-images.githubusercontent.com/53067795/108012209-caa71780-7043-11eb-81c4-e7c11943ee25.png)
想问问是怎么回事？

**Comment by nielinjie** [comment]
我猜不应该用sb init，应该是clone、npm install、npm run storybook的节奏。

**Comment by nightlye** [comment]
我又来了。这次按照clone,npm install, npm run storybook的顺序，但浏览器并没弹出什么窗口
附上操作开始的所有终端信息。
![image](https://user-images.githubusercontent.com/53067795/108022086-d9e58f80-705a-11eb-9fd9-4fe0f7414a67.png)

**Comment by nielinjie** [comment]
呃，我的错，没说完整。因为有些东西是ts写的，需要要先tsc一下。
1. clone
2. `npm install`
3. `tsc`
4. `npm run storybook`

**Comment by nightlye** [comment]
使用了tsc之后少了不少报错信息，但仍然有报错。
![image](https://user-images.githubusercontent.com/53067795/108065079-75e1bc00-7098-11eb-9118-086d292764af.png)

**Comment by nielinjie** [comment]
1. ./src 里面有两个css，需要copy到dist目录。
2. 跟windows下面文件名不区分大小写有关。看下./stories/transform.js的名字大小写。

**Comment by nielinjie** [comment]
上了个新commit，希望可以解决这些问题。
1. clone
2. npm install
3. npm run build
4. npm run storybook

**Comment by nightlye** [comment]
终于弹出storybook了。
不过这个样子好像和我想象中的大纲编辑器不太一样？
![image](https://user-images.githubusercontent.com/53067795/108080021-679c9b80-70aa-11eb-9e26-afaa8e8e8ddd.png)

**Comment by nightlye** [comment]
> 终于弹出storybook了。
> 不过这个样子好像和我想象中的大纲编辑器不太一样？
> ![image](https://user-images.githubusercontent.com/53067795/108080021-679c9b80-70aa-11eb-9e26-afaa8e8e8ddd.png)

点击左边的栏目倒是出现了树形框，我尝试编辑了一下。
因为没看到软件具体样式，所以这个就算是运行成功了吗？
![image](https://user-images.githubusercontent.com/53067795/108080585-00cbb200-70ab-11eb-9325-20604b93b9ad.png)

**Comment by nielinjie** [comment]
对呀，这个就是个react component，不是一个完整运行的软件。

**Comment by nightlye** [comment]
> 对呀，这个就是个react component，不是一个完整运行的软件。

怎么样调整到完整运行的软件界面呢

**Comment by nielinjie** [comment]
> > 对呀，这个就是个react component，不是一个完整运行的软件。
> 
> 怎么样调整到完整运行的软件界面呢

https://mindkitmap.github.io/main/#/
